import { PdbFile } from './types';

export const PDB_FILES_DIALOG: PdbFile[] = [
  { id: 'FourPlanes', name: 'Four Planes 1', description: 'Four Planes in the CPS Space.' },
  { id: 'pdb/Sphere_01', name: 'Sphere_01', description: 'Sphere_01 in the CPS Space.' },
  { id: 'pdb/Sphere_02', name: 'Sphere_02', description: 'Sphere_02 in the CPS Space.' },
  { id: 'pdb/Sphere_03', name: 'Sphere_03', description: 'Sphere_03 in the CPS Space.' },
  { id: 'pdb/Sphere_04', name: 'Sphere_04', description: 'Sphere_04 in the CPS Space.' },
  { id: 'pdb/Sphere_05', name: 'Sphere_05', description: 'Sphere_05 in the CPS Space.' },
  { id: 'pdb/Sphere_06', name: 'Sphere_06', description: 'Sphere_06 in the CPS Space.' },    
  { id: 'pdb/Sphere_07', name: 'Sphere_07', description: 'Sphere_07 in the CPS Space.' },
  { id: 'pdb/Sphere_08', name: 'Sphere_08', description: 'Sphere_08 in the CPS Space.' },
  { id: 'pdb/Sphere_09', name: 'Sphere_09', description: 'Sphere_09 in the CPS Space.' },
  { id: 'pdb/Sphere_10', name: 'Sphere_10', description: 'Sphere_10 in the CPS Space.' },
  { id: 'pdb/Sphere_11', name: 'Sphere_11', description: 'Sphere_11 in the CPS Space.' },
  { id: 'pdb/Sphere_12', name: 'Sphere_12', description: 'Sphere_12 in the CPS Space.' },
  { id: 'pdb/Sphere_13', name: 'Sphere_13', description: 'Sphere_13 in the CPS Space.' },
  { id: 'pdb/Sphere_14', name: 'Sphere_14', description: 'Sphere_14 in the CPS Space.' },
  { id: 'pdb/Sphere_15', name: 'Sphere_15', description: 'Sphere_15 in the CPS Space.' },
  { id: 'pdb/Sphere_16', name: 'Sphere_16', description: 'Sphere_16 in the CPS Space.' },    
  { id: 'pdb/Sphere_17', name: 'Sphere_17', description: 'Sphere_17 in the CPS Space.' },
  { id: 'pdb/Sphere_18', name: 'Sphere_18', description: 'Sphere_18 in the CPS Space.' },
  { id: 'pdb/Sphere_19', name: 'Sphere_19', description: 'Sphere_19 in the CPS Space.' },
  { id: 'pdb/Sphere_20', name: 'Sphere_20', description: 'Sphere_20 in the CPS Space.' },
  { id: 'pdb/Sphere_21', name: 'Sphere_21', description: 'Sphere_21 in the CPS Space.' },
  { id: 'pdb/Sphere_22', name: 'Sphere_22', description: 'Sphere_22 in the CPS Space.' },
  { id: 'pdb/Sphere_23', name: 'Sphere_23', description: 'Sphere_23 in the CPS Space.' },
  { id: 'pdb/Sphere_24', name: 'Sphere_24', description: 'Sphere_24 in the CPS Space.' },
  { id: 'pdb/Sphere_25', name: 'Sphere_25', description: 'Sphere_25 in the CPS Space.' },
  { id: 'pdb/Sphere_26', name: 'Sphere_26', description: 'Sphere_26 in the CPS Space.' },
  { id: 'pdb/Sphere_27', name: 'Sphere_27', description: 'Sphere_27 in the CPS Space.' },
  { id: 'pdb/Sphere_28', name: 'Sphere_28', description: 'Sphere_28 in the CPS Space.' },  
  { id: 'pdb/Sphere_29', name: 'Sphere_29', description: 'Sphere_29 in the CPS Space.' },
  { id: 'pdb/Sphere_30', name: 'Sphere_30', description: 'Sphere_30 in the CPS Space.' },
  { id: 'pdb/Sphere_31', name: 'Sphere_31', description: 'Sphere_31 in the CPS Space.' },
  { id: 'pdb/Sphere_32', name: 'Sphere_32', description: 'Sphere_32 in the CPS Space.' },
  { id: 'pdb/Sphere_33', name: 'Sphere_33', description: 'Sphere_33 in the CPS Space.' }, 
  { id: 'pdb/Sphere_34', name: 'Sphere_34', description: 'Sphere_34 in the CPS Space.' },
  { id: 'pdb/Sphere_35', name: 'Sphere_35', description: 'Sphere_35 in the CPS Space.' },
  { id: 'pdb/Sphere_36', name: 'Sphere_36', description: 'Sphere_36 in the CPS Space.' },
  { id: 'pdb/Sphere_37', name: 'Sphere_37', description: 'Sphere_37 in the CPS Space.' },
  { id: 'pdb/Sphere_38', name: 'Sphere_38', description: 'Sphere_38 in the CPS Space.' },  
  { id: 'pdb/Sphere_39', name: 'Sphere_39', description: 'Sphere_39 in the CPS Space.' },
  { id: 'pdb/Sphere_40', name: 'Sphere_40', description: 'Sphere_40 in the CPS Space.' },  
];
